# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VectradeCli < Formula
  desc "VecTrade CLI — financial data from your terminal"
  homepage "https://github.com/VecTrade-io/vectrade-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v0.1.0/vectrade-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4d7e508e1310495f7ab7e7250c03f9be9912f00d131332ba3d157367375a0504"

      define_method(:install) do
        bin.install "vectrade"
        bash_completion.install "completions/vectrade.bash" => "vectrade"
        zsh_completion.install "completions/vectrade.zsh" => "_vectrade"
        fish_completion.install "completions/vectrade.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v0.1.0/vectrade-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "f8eb2fd7e8ae11eab5be143fb7428ddba0b7313dbc9f9db8664633c04482a733"

      define_method(:install) do
        bin.install "vectrade"
        bash_completion.install "completions/vectrade.bash" => "vectrade"
        zsh_completion.install "completions/vectrade.zsh" => "_vectrade"
        fish_completion.install "completions/vectrade.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v0.1.0/vectrade-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "05e8d96ae5f7c2a6aea7d9d080570408fdb21c4c70c66714c9bb4fb7bcf2405a"
      define_method(:install) do
        bin.install "vectrade"
        bash_completion.install "completions/vectrade.bash" => "vectrade"
        zsh_completion.install "completions/vectrade.zsh" => "_vectrade"
        fish_completion.install "completions/vectrade.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v0.1.0/vectrade-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "45b4cfffd137822b758e3bbe327ca31af5b36a280ac8a29316a893be324e06e0"
      define_method(:install) do
        bin.install "vectrade"
        bash_completion.install "completions/vectrade.bash" => "vectrade"
        zsh_completion.install "completions/vectrade.zsh" => "_vectrade"
        fish_completion.install "completions/vectrade.fish"
      end
    end
  end

  test do
    system "#{bin}/vectrade", "version"
  end
end
