# typed: false
# frozen_string_literal: true

# Formula for the VecTrade CLI — financial data from your terminal.
# Auto-generated by GoReleaser. DO NOT EDIT.
class Vectrade < Formula
  desc "VecTrade CLI — financial data from your terminal"
  homepage "https://github.com/VecTrade-io/vectrade-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v#{version}/vectrade-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_AMD64"
    end

    on_arm do
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v#{version}/vectrade-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v#{version}/vectrade-cli_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_AMD64"
    end

    on_arm do
      url "https://github.com/VecTrade-io/vectrade-cli/releases/download/v#{version}/vectrade-cli_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
  end

  def install
    bin.install "vectrade"
    bash_completion.install "completions/vectrade.bash" => "vectrade"
    zsh_completion.install "completions/vectrade.zsh" => "_vectrade"
    fish_completion.install "completions/vectrade.fish"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vectrade version")
    assert_match "Usage:", shell_output("#{bin}/vectrade --help")
  end
end
